apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "main-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ include "main-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "main-app.name" . }}
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      serviceAccountName: {{ include "main-app.fullname" . }}
      containers:
        - name: main-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: MICROSERVICE_URL
              value: {{ .Values.env.MICROSERVICE_URL }}