{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "main-app.fullname" . }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/main-app-irsa-role
{{- end }}