replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3001

resources:
  requests:
    cpu: "150m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "300Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70

externalSecret:
  enabled: false
  name: aws-secrets-manager
  refreshInterval: 1m
  secretStoreName: aws-secrets-manager
  targetSecretName: dev-microservice-app-env

podDisruptionBudget:
  minAvailable: 1

serviceAccount:
  create: true
  name: "sa-microapp"

env:
  MICROSERVICE_URL: http://microservice.dev.svc.cluster.local:3001