{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice.fullname" . }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/microservice-irsa-role
{{- end }}