apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::071564830585:role/eks-cluster-v2-main-eks-node-group-20260228212140983900000003
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::071564830585:role/GITHUB_ROLE
      username: github-actions
      groups:
        - system:masters
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::071564830585:role/eks-access-developer-role
      username: dev-users
      groups:
        - developers
kind: ConfigMap
metadata:
  creationTimestamp: "2026-02-28T19:01:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "219053"
  uid: 4ba42f64-9b4c-4c9e-8514-a6344129e739